import type { Scene } from "./types";

export const textRefusalScene: Scene = {
  id: "text-refusal",
  title: "Текст: отказ дешёв",
  actors: [
    { id: "a", label: "A" },
    { id: "b", label: "B" },
  ],
  nodes: [
    {
      id: "text-message",
      type: "Message",
      label: "«Можешь отказаться»",
      epistemic: "observed",
      level: 1,
      actorId: "a",
      ui: { x: 180, y: 176 },
    },
    {
      id: "text-rule",
      type: "Rule",
      label: "Отказ формально допустим",
      epistemic: "inferred",
      level: 2,
      ui: { x: 450, y: 294 },
    },
  ],
  edges: [
    {
      id: "text-e1",
      from: "text-message",
      to: "text-rule",
      type: "permits",
    },
  ],
  moves: [
    { id: "refuse", label: "Отказать", kind: "action", level: 0 },
    { id: "accept", label: "Согласиться", kind: "action", level: 0 },
  ],
  operators: [
    {
      id: "text-permission",
      type: "permits",
      label: "Текстовое разрешение снижает стоимость отказа",
      sourceActorId: "a",
      targetActorId: "b",
      channel: "text",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "relief",
        magnitude: 18,
        conductance: 0.85,
        gain: 1,
        reality: "expected",
      },
      epistemic: "observed",
    },
    {
      id: "text-latency",
      type: "permits",
      label: "Пауза между сообщением и ответом даёт пространство метаходу",
      channel: "timing",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "relief",
        magnitude: 15,
        conductance: 0.9,
        gain: 1,
        reality: "expected",
      },
      epistemic: "inferred",
    },
  ],
  timeline: [],
};

export const presencePressureScene: Scene = {
  id: "presence-pressure",
  title: "Присутствие: отказ дорог",
  actors: [
    { id: "a", label: "A" },
    { id: "b", label: "B" },
    { id: "group", label: "Группа" },
  ],
  nodes: [
    {
      id: "presence-message",
      type: "Message",
      label: "«Можешь отказаться»",
      epistemic: "observed",
      level: 1,
      actorId: "a",
      ui: { x: 180, y: 176 },
    },
    {
      id: "presence-rule",
      type: "Rule",
      label: "Отказ формально допустим",
      epistemic: "inferred",
      level: 2,
      ui: { x: 450, y: 294 },
    },
    {
      id: "presence-context",
      type: "Context",
      label: "Личная встреча в присутствии группы",
      epistemic: "observed",
      level: 4,
      ui: { x: 700, y: 530 },
    },
  ],
  edges: [
    {
      id: "presence-e1",
      from: "presence-message",
      to: "presence-rule",
      type: "permits",
    },
  ],
  moves: [
    { id: "refuse", label: "Отказать", kind: "action", level: 0 },
    { id: "accept", label: "Согласиться", kind: "action", level: 0 },
  ],
  operators: [
    {
      id: "presence-verbal",
      type: "permits",
      label: "Словами отказ разрешён",
      sourceActorId: "a",
      targetActorId: "b",
      channel: "verbal",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "relief",
        magnitude: 15,
        conductance: 0.7,
        gain: 1,
        reality: "expected",
      },
      epistemic: "observed",
    },
    {
      id: "presence-gaze",
      type: "sanctions",
      label: "Взгляд делает отказ социально дорогим",
      sourceActorId: "a",
      targetActorId: "b",
      channel: "gaze",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "cost",
        magnitude: 30,
        conductance: 0.95,
        gain: 1.2,
        reality: "expected",
      },
      epistemic: "observed",
    },
    {
      id: "presence-prosody",
      type: "sanctions",
      label: "Интонация противоречит словесному разрешению",
      sourceActorId: "a",
      targetActorId: "b",
      channel: "prosody",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "cost",
        magnitude: 20,
        conductance: 0.85,
        gain: 1.1,
        reality: "expected",
      },
      epistemic: "observed",
    },
    {
      id: "presence-proximity",
      type: "sanctions",
      label: "Физическая близость увеличивает цену сопротивления",
      sourceActorId: "a",
      targetActorId: "b",
      channel: "proximity",
      target: { kind: "move", id: "refuse" },
      influence: {
        moveId: "refuse",
        direction: "cost",
        magnitude: 18,
        conductance: 0.9,
        gain: 1.1,
        reality: "expected",
      },
      epistemic: "inferred",
    },
    {
      id: "presence-group",
      type: "reinforces",
      label: "Реакция группы усиливает сигнал статуса",
      sourceActorId: "group",
      targetActorId: "b",
      channel: "group-response",
      target: { kind: "operator", id: "presence-gaze" },
      influence: {
        moveId: "refuse",
        direction: "cost",
        magnitude: 15,
        conductance: 0.9,
        gain: 1.5,
        reality: "expected",
      },
      epistemic: "inferred",
    },
  ],
  timeline: [],
};
