import type { Scene } from "./types";

export const spontaneousScene: Scene = {
  id: "spontaneous-command",
  title: "Будь спонтанным",
  actors: [
    { id: "a", label: "A" },
    { id: "b", label: "B" },
  ],
  nodes: [
    {
      id: "message",
      type: "Message",
      label: "«Будь спонтанным»",
      epistemic: "observed",
      level: 1,
      actorId: "a",
      ui: { x: 160, y: 176 },
    },
    {
      id: "rule-comply",
      type: "Rule",
      label: "R1: выполни просьбу",
      epistemic: "inferred",
      level: 2,
      ui: { x: 270, y: 294 },
    },
    {
      id: "rule-spontaneous",
      type: "Rule",
      label: "R2: спонтанность не может быть выполнением команды",
      epistemic: "inferred",
      level: 2,
      ui: { x: 540, y: 294 },
    },
    {
      id: "sanction-comply",
      type: "Sanction",
      label: "Выполнение по команде отменяет «спонтанность»",
      epistemic: "inferred",
      level: 2,
      metadata: { severity: 3 },
      ui: { x: 770, y: 294 },
    },
    {
      id: "sanction-refuse",
      type: "Sanction",
      label: "Отказ означает невыполнение просьбы",
      epistemic: "inferred",
      level: 2,
      metadata: { severity: 3 },
      ui: { x: 40, y: 294 },
    },
    {
      id: "meta-gate",
      type: "Gate",
      label: "MetaGate: обсуждать противоречие",
      epistemic: "observed",
      level: 3,
      metadata: { gateType: "meta", gateStatus: "closed" },
      ui: { x: 270, y: 412 },
    },
    {
      id: "exit-gate",
      type: "Gate",
      label: "ExitGate: выйти из рамки",
      epistemic: "observed",
      level: 4,
      metadata: { gateType: "exit", gateStatus: "closed" },
      ui: { x: 540, y: 530 },
    },
  ],
  edges: [
    { id: "e1", from: "message", to: "rule-comply", type: "requires" },
    {
      id: "e2",
      from: "message",
      to: "rule-spontaneous",
      type: "interpretsAs",
    },
    {
      id: "e3",
      from: "rule-comply",
      to: "rule-spontaneous",
      type: "contradicts",
    },
    {
      id: "e4",
      from: "rule-spontaneous",
      to: "sanction-comply",
      type: "sanctions",
    },
    {
      id: "e5",
      from: "rule-comply",
      to: "sanction-refuse",
      type: "sanctions",
    },
    { id: "e6", from: "meta-gate", to: "rule-comply", type: "blocks" },
    {
      id: "e7",
      from: "exit-gate",
      to: "rule-spontaneous",
      type: "blocks",
    },
  ],
  moves: [
    {
      id: "comply",
      label: "Выполнить просьбу",
      kind: "action",
      level: 0,
      violatesRuleIds: ["rule-spontaneous"],
      sanctionIds: ["sanction-comply"],
    },
    {
      id: "refuse",
      label: "Не выполнять просьбу",
      kind: "action",
      level: 0,
      violatesRuleIds: ["rule-comply"],
      sanctionIds: ["sanction-refuse"],
    },
    {
      id: "meta",
      label: "Назвать противоречие",
      kind: "meta",
      level: 3,
      blockedByGateIds: ["meta-gate"],
    },
    {
      id: "exit",
      label: "Выйти из рамки",
      kind: "exit",
      level: 4,
      blockedByGateIds: ["exit-gate"],
    },
  ],
};
